language: node_js
node_js: 14.5.0
notifications:
  slack: "yoyodesign:4HjysiaAvCJPeibgAYAFssht"
after_success: npm run docs
deploy:
  - provider: npm
    email: "$NPM_EMAIL"
    api_key: "$NPM_AUTH_TOKEN"
    on:
      branch: master
  - provider: pages
    skip_cleanup: true
    github_token: "$GITHUB_TOKEN"
    local_dir: docs
    on:
      branch: master
