name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Node
        uses: actions/setup-node@v2-beta
        with:
          node-version: '14'

      - name: Install
        run: npm i

      - name: Lint
        run: npm run lint

      - name: Unit
        run: npm run unit