name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2-beta
        with:
          node-version: '14'

      - name: Install NPM packages
        run: npm i

      - name: Run linter
        run: npx stylelint lib/**/*.scss

      - name: Run unit tests
        run: npm run unit